import type { Metadata } from 'next';
import { Providers } from './redux/providers';
import Header from '../components/Header';
import { DarkModeProvider } from './actions/darkModeContext';

//import localFont from "next/font/local";
import './globals.css';

import { fontLeagueSpartan, fontFredoka } from '@/components/ui/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <DarkModeProvider>
        <html lang="en">
          <body
            className={`${fontLeagueSpartan.variable} ${fontFredoka.variable} antialiased `}
          >
            <div
              className={`grid content-start grid-cols-1 xl:grid-cols-[auto]   min-h-svh text-foreground dark:text-primary-foreground
                 bg-background dark:bg-dark-background min-w-80`}
            >
              <Header />

              <main
                className={`grid justify-items-center w-full h-full content-start`}
              >
                {children}
              </main>
            </div>
          </body>
        </html>
      </DarkModeProvider>
    </Providers>
  );
}
